#!/usr/bin/env bash
# Run BrutalDots inside a nested Hyprland, in a window on your existing desktop.
#
# Nothing is installed, no config of yours is read or written, and your running
# session is untouched — the nested compositor gets its own workspaces, its own
# layer-shell surfaces and its own exclusive zones.
#
#   ./scripts/test-nested.sh              # share the session bus with your desktop
#   ./scripts/test-nested.sh --isolated   # private session bus (see below)
#   ./scripts/test-nested.sh --size 1920x1080
#
# --isolated gives the nested shell a private D-Bus session, which is the only
# way to test notifications while another shell is already running (two shells
# cannot both own org.freedesktop.Notifications). The trade-off: MPRIS is also
# session-bus scoped, so players running on your host desktop will not appear.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SIZE="1600x900"
ISOLATED=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --isolated) ISOLATED=1; shift ;;
        --size) SIZE="$2"; shift 2 ;;
        --help|-h) awk 'NR>1 && /^#/ { sub(/^# ?/, ""); print; next } NR>1 { exit }' "$0"; exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 1 ;;
    esac
done

if [[ -z "${WAYLAND_DISPLAY:-}" ]]; then
    echo "error: no WAYLAND_DISPLAY — run this from inside a Wayland session." >&2
    exit 1
fi

command -v Hyprland >/dev/null || { echo "error: Hyprland not found" >&2; exit 1; }
command -v quickshell >/dev/null || { echo "error: quickshell not found" >&2; exit 1; }

if ((ISOLATED)) && ! command -v dbus-run-session >/dev/null; then
    echo "error: --isolated needs dbus-run-session (package: dbus)" >&2
    exit 1
fi

# Pick whatever terminal is actually installed, for SUPER+Q inside the nest.
TERMINAL=""
for t in kitty alacritty foot ghostty wezterm konsole; do
    if command -v "$t" >/dev/null; then TERMINAL="$t"; break; fi
done

TERM_BIND=""
if [[ -n "$TERMINAL" ]]; then
    TERM_BIND="hl.bind(\"SUPER + Q\", hl.dsp.exec_cmd(\"$TERMINAL\"), { description = \"Terminal\" })"
fi

CONF="$(mktemp --suffix=.lua)"
trap 'rm -f "$CONF"' EXIT

# The nested config is deliberately thin: it puts the repo on Lua's module path
# and loads the real hyprland.lua, then applies session-only overrides on top.
# That way this test exercises the exact config users install.
cat > "$CONF" <<CONFIG
-- Generated by test-nested.sh - throwaway config for a nested session.
package.path = "${REPO}/.config/hypr/?.lua;${REPO}/.config/hypr/?/init.lua;" .. package.path

require("hyprland")

-- Session-only overrides, applied after the real config so they win.
hl.monitor({ output = "", mode = "${SIZE}@60", position = "0x0", scale = 1 })

hl.bind("SUPER + SHIFT + E", hl.dsp.exit(), { description = "Quit nested session" })
${TERM_BIND}
CONFIG

if ! Hyprland --verify-config -c "$CONF" 2>&1 | grep "config ok" >/dev/null; then
    echo "error: generated nested config is invalid:" >&2
    Hyprland --verify-config -c "$CONF" 2>&1 | tail -3 >&2
    exit 1
fi

cat <<MSG

  BrutalDots — nested test session (${SIZE})

    SUPER + D        dashboard
    SUPER + W        widgets
    SUPER + ESC      power menu
$( [[ -n "$TERMINAL" ]] && echo "    SUPER + Q        $TERMINAL" )
    SUPER + 1..5     switch workspace
    SUPER + SHIFT+E  quit the nested session

  Session bus: $( ((ISOLATED)) && echo "private (notifications testable)" || echo "shared (MPRIS from your desktop works)" )

MSG

# Point the config at this checkout instead of an installed shell.
export BRUTALDOTS_SHELL_CMD="qs -p ${REPO}/.config/quickshell/brutal"

if ((ISOLATED)); then
    dbus-run-session -- Hyprland -c "$CONF"
else
    Hyprland -c "$CONF"
fi
